### ISSUE TITLE
Import error.

### ISSUE THREAD

**Issue by PradeepSimba** [javaterminal/TerminalFX#28]
When I import this project it occurs an error.

Build :

![2](https://user-images.githubusercontent.com/45443554/83409278-bda0b480-a431-11ea-9942-f21d48ccc8df.PNG)

**Comment by PradeepSimba** [comment]
How can I solve this error?

**Comment by PradeepSimba** [comment]
when I sync it comes 

Could not transfer artifact org.jetbrains:annotations:pom:16.0.2 from/to central (http://repo1.maven.org/maven2/): Transfer failed for http://repo1.maven.org/maven2/org/jetbrains/annotations/16.0.2/annotations-16.0.2.pom 501 HTTPS Required

**Comment by rahmanusta** [comment]
I changed the http to https in maven pom file. You can pull the change and check again.

**Comment by PradeepSimba** [comment]
@rahmanusta  


When I run this project.

It comes 

`C:\Users\prade\.jdks\openjdk-14\bin\java.exe --module-path D:/install/javafx-sdk-11.0.2/lib --add-modules javafx.fxml,javafx.base,javafx.controls,javafx.graphics,javafx.media,javafx.swing,javafx.web --add-modules javafx.base,javafx.graphics --add-reads javafx.base=ALL-UNNAMED --add-reads javafx.graphics=ALL-UNNAMED "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.1.1\lib\idea_rt.jar=59746:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.1.1\bin" -Dfile.encoding=UTF-8 -m com.kodedu.terminalfx/com.kodedu.terminalfx.TerminalAppStarter
Error occurred during initialization of boot layer
java.lang.module.FindException: Module com.kodedu.terminalfx not found

Process finished with exit code 1
`

**Comment by PradeepSimba** [comment]
Error occurred during initialization of boot layer
java.lang.module.FindException: Module com.kodedu.terminalfx not found

**Comment by PradeepSimba** [comment]
When I run this in netbeans .

![netbeans](https://user-images.githubusercontent.com/45443554/83720586-f40b4900-a656-11ea-8672-ab4b95da70d4.PNG)

`cd D:\Github\TerminalFX; "JAVA_HOME=C:\\Program Files\\Java\\jdk-13.0.2" cmd /c "\"C:\\Program Files\\NetBeans-11.3\\netbeans\\java\\maven\\bin\\mvn.cmd\" -Dexec.args=\"-classpath %classpath com.kodedu.terminalfx.TerminalAppStarter\" -Dexec.executable=\"C:\\Program Files\\Java\\jdk-13.0.2\\bin\\java.exe\" -Dexec.classpathScope=runtime -Dmaven.ext.class.path=\"C:\\Program Files\\NetBeans-11.3\\netbeans\\java\\maven-nblib\\netbeans-eventspy.jar\" -Dfile.encoding=UTF-8 process-classes org.codehaus.mojo:exec-maven-plugin:1.5.0:exec"
Scanning for projects...
                                                                        
------------------------------------------------------------------------
Building TerminalFX 1.1.0
------------------------------------------------------------------------

--- maven-resources-plugin:2.6:resources (default-resources) @ terminalfx ---
Using 'UTF-8' encoding to copy filtered resources.
Copying 4 resources

--- maven-compiler-plugin:3.8.0:compile (default-compile) @ terminalfx ---
********************************************************************************************************************
* Required filename-based automodules detected. Please don't publish this project to a public artifact repository! *
********************************************************************************************************************
Changes detected - recompiling the module!
Compiling 14 source files to D:\Github\TerminalFX\target\classes

--- exec-maven-plugin:1.5.0:exec (default-cli) @ terminalfx ---
Error: JavaFX runtime components are missing, and are required to run this application
Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
	at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:764)
	at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:711)
	at org.codehaus.mojo.exec.ExecMojo.execute(ExecMojo.java:289)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
------------------------------------------------------------------------
BUILD FAILURE
------------------------------------------------------------------------
Total time: 13.777 s
Finished at: 2020-06-04T11:17:54+05:30
Final Memory: 18M/64M
------------------------------------------------------------------------
Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.5.0:exec (default-cli) on project terminalfx: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

For more information about the errors and possible solutions, please read the following articles:
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
`

Help !!!!

**Comment by ashokkumarvel** [comment]
I also have the same error.

**Comment by rahmanusta** [comment]
We don't support Java 14 yet. Use version 12 in both jdk and javafx.

**Comment by PradeepSimba** [comment]
https://github.com/javaterminal/TerminalFX/issues/33#issue-648711979

Help!!!
