### ISSUE TITLE
Error occurred during initialization of boot layer

### ISSUE THREAD

**Issue by ashokkumarvel** [javaterminal/TerminalFX#31]
Whwn I run it comes an error.

`Error occurred during initialization of boot layer
java.lang.module.FindException: Module com.kodedu.terminalfx not found

**Comment by ashokkumarvel** [comment]
`Error occurred during initialization of boot layer
java.lang.module.FindException: Module = not found
Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
	at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:764)
	at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:711)
	at org.codehaus.mojo.exec.ExecMojo.execute(ExecMojo.java:289)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
------------------------------------------------------------------------
BUILD FAILURE`

**Comment by rahmanusta** [comment]
How do you run it ?

**Comment by ashokkumarvel** [comment]
My project structure.

![pstr](https://user-images.githubusercontent.com/65845270/86115490-a533c080-bae9-11ea-9c13-9b30f32f0dcd.PNG)

Error

![err](https://user-images.githubusercontent.com/65845270/86115801-0cea0b80-baea-11ea-9332-f507dd8906cb.PNG)

`C:\Users\prade\.jdks\openjdk-14\bin\java.exe --module-path D:/install/javafx-sdk-11.0.2/lib --add-modules javafx.fxml,javafx.base,javafx.controls,javafx.graphics,javafx.media,javafx.swing,javafx.web --add-modules javafx.base,javafx.graphics --add-reads javafx.base=ALL-UNNAMED --add-reads javafx.graphics=ALL-UNNAMED "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.1.1\lib\idea_rt.jar=57877:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.1.1\bin" -Dfile.encoding=UTF-8 -m com.kodedu.terminalfx/com.kodedu.terminalfx.TerminalAppStarter
Error occurred during initialization of boot layer
java.lang.module.FindException: Module com.kodedu.terminalfx not found

Process finished with exit code 1

`
What mistook I did in this ?

Hlep me !!!

**Comment by PradeepSimba** [comment]
Help !!!

https://github.com/javaterminal/TerminalFX/issues/31#issuecomment-651707521

**Comment by rahmanusta** [comment]
We don't support Java 14 yet. Use version 12 in both jdk and javafx.

**Comment by PradeepSimba** [comment]
https://github.com/javaterminal/TerminalFX/issues/33#issue-648711979

Help!!!
