### ISSUE TITLE
Usage Issue

### ISSUE THREAD

**Issue by ghost** [javaterminal/TerminalFX#4]
I know this isn't an issue with your program itself, but can someone help me with this error?

```
Caused by: netscape.javascript.JSException: ReferenceError: Can't find variable: t
	at com.sun.webkit.dom.JSObject.fwkMakeException(JSObject.java:128)
	at com.sun.webkit.WebPage.twkExecuteScript(Native Method)
	at com.sun.webkit.WebPage.executeScript(WebPage.java:1455)
	at javafx.scene.web.WebEngine.executeScript(WebEngine.java:982)
	at com.kodedu.terminalfx.TerminalTab.getTerminalIO(TerminalTab.java:238)
	at com.kodedu.terminalfx.TerminalTab.lambda$print$9(TerminalTab.java:221)
	at com.kodedu.terminalfx.helper.ThreadHelper.runActionLater(ThreadHelper.java:22)
	at com.kodedu.terminalfx.TerminalTab.print(TerminalTab.java:220)
```

Am I missing a dependency? This is what I have: https://i.imgur.com/zbe0MLJ.png

**Comment by Wonderlus** [comment]
**Usage:**

```
        TerminalBuilder terminalBuilder = new TerminalBuilder();
        terminalBuilder.setNameGenerator(TERMINAL_NAME_GENERATOR);

        TerminalTab terminal1 = terminalBuilder.newTerminal();
        TerminalTab terminal2 = terminalBuilder.newTerminal();
        TerminalTab terminal3 = terminalBuilder.newTerminal();
        TerminalTab terminal4 = terminalBuilder.newTerminal();

        TabPane tabPane = new TabPane();
        tabPane.getTabs().add(terminal1);
        tabPane.getTabs().add(terminal2);
        tabPane.getTabs().add(terminal3);
        tabPane.getTabs().add(terminal4);

        tabPane.setLayoutX(10);
        tabPane.setLayoutY(294);
        tabPane.setPrefSize(880, 297);
        root.getChildren().add(tabPane);

        terminal1.print("Testing 1. 2.. 3...");
```

I'm trying to add your terminal as a component to my application. Is this possible?

**Comment by rahmanusta** [comment]
Remove terminal1.print("Testing 1. 2.. 3..."); print is not intended to use directly.

**Comment by rahmanusta** [comment]
You can run commands like here https://github.com/javaterminal/TerminalFX#7-run-command
