### ISSUE TITLE
not ready  exception

### ISSUE THREAD

**Issue by zhangxuehong** [javaterminal/TerminalFX#7]
java.lang.RuntimeException: Terminal is not ready yet.
	at com.kodedu.terminalfx.TerminalTab.print(TerminalTab.java:239)
	at com.kodedu.terminalfx.TerminalTab.printReader(TerminalTab.java:332)
	at com.kodedu.terminalfx.TerminalTab.lambda$13(TerminalTab.java:291)
	at java.lang.Thread.run(Thread.java:748)

i can't find pty4j through maven,so i find the jar from https://github.com/javaterminal/pty4j and what the pty4j needed at https://github.com/traff/pty4j/tree/master/lib  . but when i start , it throws this exception,  oh, don't know how do deal with with it.  could you healp me to keep this code running normal?

**Comment by rahmanusta** [comment]
Hi @zhangxuehong , you can use it like below; (Use v 1.0.5)

https://github.com/javaterminal/TerminalFX#7-run-command
